language: node_js
node_js:
  - "4.8.1"
cache:
   directories:
      - node_modules
      - $HOME/.meteor/

before_install:
   - export PATH="$HOME/.meteor:$PATH"
   - curl https://install.meteor.com | /bin/sh
script:
  - npm run cli
